pool:
  name: 'linux-agent'
     
 
stages:
- stage: DockerBuild
  displayName: "Build and Push Ubuntu 22.04 Docker Image"
  jobs:
  - job: BuildAndPush
    displayName: "Build and Push to ACR"
    steps:
    - task: Docker@2
      displayName: "Login to ACR"
      inputs:
        command: login
        containerRegistry: 'kolkata'   
    - task: Docker@2
      displayName: "Build and Push Ubuntu Image"
      inputs:
        command: buildAndPush
        containerRegistry: 'kolkata'   
        repository: poco   
        dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest